package com.rohittp.reng.internal.image

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotEquals

// Every fixture below is a real, valid PNG generated once via CPython's zlib/struct/zlib.crc32
// modules and pasted as a byte literal, so every target's test task asserts against the exact same
// bytes rather than recomputing an expectation with the same decoder code under test. The five-way
// forward row filter (undoing what PngDecoder.kt's `unfilter` must reverse) and the Paeth predictor
// are hand-reimplemented in that script from the PNG specification, independently of the Kotlin
// decoder, per the same anti-circularity bar Task 4's fixtures were held to. Regenerate with:
//
// python3 - <<'PY'
// import zlib, struct
// SIG = b"\x89PNG\r\n\x1a\n"
// def chunk(kind, payload):
//     return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", zlib.crc32(kind + payload) & 0xffffffff)
// def ihdr_payload(w, h, depth, colour, compression=0, filt=0, interlace=0):
//     return struct.pack(">IIBBBBB", w, h, depth, colour, compression, filt, interlace)
// def build_png(w, h, depth, colour, idat_payloads, extra_chunks_after_ihdr=(), plte=None, trns=None):
//     out = SIG + chunk(b"IHDR", ihdr_payload(w, h, depth, colour))
//     for c in extra_chunks_after_ihdr:
//         out += c
//     if plte is not None:
//         out += chunk(b"PLTE", plte)
//     if trns is not None:
//         out += chunk(b"tRNS", trns)
//     for payload in idat_payloads:
//         out += chunk(b"IDAT", payload)
//     return out + chunk(b"IEND", b"")
// def paeth_predictor(a, b, c):
//     p = a + b - c
//     pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
//     return a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
// def forward_filter_row(filter_type, cur_row, prev_row, bpp):
//     out = bytearray(len(cur_row))
//     for i in range(len(cur_row)):
//         x = cur_row[i]
//         a = cur_row[i - bpp] if i >= bpp else 0
//         b = prev_row[i] if prev_row is not None else 0
//         c = prev_row[i - bpp] if (prev_row is not None and i >= bpp) else 0
//         if filter_type == 0: out[i] = x & 0xFF
//         elif filter_type == 1: out[i] = (x - a) & 0xFF
//         elif filter_type == 2: out[i] = (x - b) & 0xFF
//         elif filter_type == 3: out[i] = (x - ((a + b) // 2)) & 0xFF
//         else: out[i] = (x - paeth_predictor(a, b, c)) & 0xFF
//     return bytes(out)
// def build_filtered_raw(rows, bpp, filter_type):
//     out, prev = bytearray(), None
//     for row in rows:
//         out += bytes([filter_type]) + forward_filter_row(filter_type, row, prev, bpp)
//         prev = row
//     return bytes(out)
// # ... see task-5-report.md for the full script, including the deliberately-embedded Paeth ties.
// PY
class PngDecoderTest {
    @Test
    fun decodesEveryFilterTypeExactly() {
        // One fixture per filter byte 0..4, each 4x4 RGB, all encoding the same pixels. The pixel
        // grid deliberately embeds two genuine (non-boundary) Paeth predictor ties — at (row=1,col=1,R)
        // a=0,b=3,c=2 (a must win over the tie with c) and at (row=3,col=1,G) a=0,b=3,c=1 (b must win
        // over the tie with c) — so filterPaethFixture actually pins the specified tie-break order
        // rather than merely exercising Paeth arithmetic. Verified independently: a deliberately
        // flipped tie-break decoder (c wins ties, then b, then a) reconstructs different bytes at both
        // embedded positions, so this test would fail under that bug.
        for ((name, bytes) in filterFixtures) {
            val result = assertIs<PngDecodeResult.Success>(decodePng(bytes, 1L shl 20), name)
            assertContentEquals(expectedFilterPixels, result.image.rgbaSnapshot(), name)
        }
    }

    @Test
    fun widensGreyscaleAndPaletteLosslessly() {
        val grey = assertIs<PngDecodeResult.Success>(decodePng(grey8TwoPixels, 1L shl 20))
        assertContentEquals(
            byteArrayOf(0x40, 0x40, 0x40, -1, -0x80, -0x80, -0x80, -1),
            grey.image.rgbaSnapshot(),
        )
        val palette = assertIs<PngDecodeResult.Success>(decodePng(paletteWithTrns, 1L shl 20))
        assertContentEquals(
            byteArrayOf(-1, 0, 0, -1, 0, 0, -1, -0x80),
            palette.image.rgbaSnapshot(),
        )
    }

    @Test
    fun rejectsAFilterByteAboveFour() {
        assertIs<PngDecodeResult.Malformed>(decodePng(filterByteFive, 1L shl 20))
    }

    @Test
    fun rejectsAStreamThatEndsEarlyOrRunsLong() {
        // IMAGE_DATA_LENGTH: the chunk lengths themselves are fine here — it's the decompressed
        // content that mismatches the declared raster, a different layer from a container-framing
        // fault, so this does not reuse CHUNK_LENGTH.
        assertEquals(PngReject.IMAGE_DATA_LENGTH, malformedReasonOf(deflateShorterThanRaster))
        assertEquals(PngReject.IMAGE_DATA_LENGTH, malformedReasonOf(deflateLongerThanRaster))
    }

    @Test
    fun decidesTheCeilingFromHeaderDimensionsBeforeAllocating() {
        // 4096x4096 RGBA is 67_108_864 bytes; the declared ceiling is one byte short.
        assertIs<PngDecodeResult.TooLarge>(decodePng(declared4096Square, 67_108_863L))
        // The same header passes when the ceiling admits it, proving the check is on dimensions.
        assertIs<PngDecodeResult.Success>(decodePng(declared4096Square, 67_108_864L))
    }

    @Test
    fun decidesThePeakWorkingCeilingBeforeAllocating() {
        // 4x4 RGBA output is 64 bytes. The bounded upload workspace for this tiny image is another
        // 64 bytes (larger than the two 13-byte RGB row buffers), for a projected peak of 128.
        assertEquals(64L, projectedPngRgbaBytes(filterNoneFixture))
        assertIs<PngDecodeResult.TooLarge>(decodePng(filterNoneFixture, 1L shl 20, 127L))
        assertIs<PngDecodeResult.Success>(decodePng(filterNoneFixture, 1L shl 20, 128L))
    }

    @Test
    fun appliesNoColourTransformForAnyAncillaryColourChunk() {
        val plain = assertIs<PngDecodeResult.Success>(decodePng(rgb8Reference, 1L shl 20))
        // Pin the reference decode against an independently-computed expectation first, so the loop
        // below is proving every ancillary variant agrees with the TRUE pixels, not merely with
        // whatever `plain` happened to decode to.
        assertContentEquals(expectedRgb8ReferencePixels, plain.image.rgbaSnapshot())
        for (fixture in listOf(rgb8WithGama, rgb8WithSrgb, rgb8WithIccp, rgb8WithChrm)) {
            val decoded = assertIs<PngDecodeResult.Success>(decodePng(fixture, 1L shl 20))
            assertContentEquals(plain.image.rgbaSnapshot(), decoded.image.rgbaSnapshot())
        }
    }

    @Test
    fun decodedImageCopiesOnEveryRead() {
        val image = assertIs<PngDecodeResult.Success>(decodePng(rgb8Reference, 1L shl 20)).image
        val first = image.rgbaSnapshot()
        first[0] = 0
        assertNotEquals(first[0], image.rgbaSnapshot()[0])
    }

    // Not in the brief's literal test list, but explicitly required by its Step 3 prose ("tRNS is
    // rejected for colour types 4 and 6 as Malformed") and reachable through scanPng: scanPng captures
    // any tRNS chunk regardless of colour type and only rejects PLTE-on-0/4 (PALETTE_FORBIDDEN), so a
    // colour-type-4-or-6 file carrying tRNS reaches PngScan.Admitted and this decoder must reject it
    // itself. TRNS_FORBIDDEN, not PALETTE_FORBIDDEN: colour types 4 and 6 never carry a PLTE at all, so
    // "palette" would be false of this fault and would send a reader looking at the wrong chunk.
    @Test
    fun rejectsTrnsForColourTypesThatAlreadyCarryAlpha() {
        assertEquals(PngReject.TRNS_FORBIDDEN, malformedReasonOf(greyAlphaWithForbiddenTrns))
        assertEquals(PngReject.TRNS_FORBIDDEN, malformedReasonOf(rgbaWithForbiddenTrns))
    }

    // A small PLTE (one entry) plus a raster index byte that indexes past it. scanPng only checks that
    // colour type 3 has SOME palette, never that every index a raster contains fits it, so this reaches
    // widenToRgba, which must reject rather than crash with ArrayIndexOutOfBoundsException.
    @Test
    fun rejectsAPaletteIndexOutOfRange() {
        assertEquals(PngReject.PALETTE_INDEX_OUT_OF_RANGE, malformedReasonOf(paletteIndexOutOfRange))
    }

    // A declared IHDR width of 0x80000000 (2^31) — the PNG specification's valid dimension range is 1
    // to 2^31-1, and this value wraps to a negative Int under the container's unchecked 32-bit
    // reinterpretation. Without PngContainer.kt's DIMENSION_OUT_OF_RANGE check, this same fixture
    // crashes rather than failing an assertion: `width.toLong() * height.toLong() * 4L` sign-extends to
    // a large negative Long, so it is never `> maximumDecodedBytes` and the TooLarge gate never fires;
    // downstream `rawSizeLong.toInt()` goes negative and `ByteArray(expectedSize + 1)` throws
    // NegativeArraySizeException. Confirmed by temporarily removing that check and observing exactly
    // that crash (see task-5-report.md) rather than this assertion failing — the fix is load-bearing.
    @Test
    fun rejectsADimensionThatWrapsToANegativeInt() {
        assertEquals(PngReject.DIMENSION_OUT_OF_RANGE, malformedReasonOf(dimensionOutOfRange))
    }

    // scanPng validates tRNS's length for colour types 0 and 2 (exactly 2 and 6 bytes respectively) but
    // did not before this fix round: an empty or wrongly-sized tRNS is not null, so it used to sail past
    // a null-only check and crash inside greyKeyAlpha/rgbKeyAlpha's transparency[1]/[3]/[5] reads with
    // ArrayIndexOutOfBoundsException. TRNS_LENGTH, not TRNS_FORBIDDEN: tRNS is not forbidden on these
    // colour types, it is merely the wrong size, and "forbidden" would send a consumer to delete a chunk
    // they are entitled to have. Confirmed by temporarily removing scanPng's new length check and
    // observing greyTrnsWrongLength crash rather than fail an assertion (see task-5-report.md).
    @Test
    fun rejectsTrnsLengthMismatchForColourTypesZeroAndTwo() {
        assertEquals(PngReject.TRNS_LENGTH, malformedReasonOf(greyTrnsWrongLength))
        assertEquals(PngReject.TRNS_LENGTH, malformedReasonOf(rgbTrnsWrongLength))
    }

    // Positive counterpart to the two rejections above: a correctly-sized tRNS (2 bytes for colour type
    // 0, 6 for colour type 2) must still decode, with the keyed pixel transparent and every other pixel
    // opaque. Without this, a check that rejected every tRNS on these colour types would also pass the
    // negative test above for the wrong reason.
    @Test
    fun appliesTrnsColourKeyForGreyscaleAndTruecolour() {
        val grey = assertIs<PngDecodeResult.Success>(decodePng(greyTwoPixelsWithTrnsKey, 1L shl 20))
        assertContentEquals(expectedGreyTwoPixelsWithTrnsKey, grey.image.rgbaSnapshot())

        val rgb = assertIs<PngDecodeResult.Success>(decodePng(rgbTwoPixelsWithTrnsKey, 1L shl 20))
        assertContentEquals(expectedRgbTwoPixelsWithTrnsKey, rgb.image.rgbaSnapshot())
    }

    // Colour type 3's tRNS may legitimately be SHORTER than its palette — missing entries default
    // opaque, per specification — and that leniency (decode-time paletteAlpha) must not be broken by
    // this fix round's length validation, which deliberately excludes colour type 3.
    @Test
    fun palettesShortTrnsLeavesRemainingEntriesOpaque() {
        val result = assertIs<PngDecodeResult.Success>(decodePng(paletteWithShortTrns, 1L shl 20))
        assertContentEquals(expectedPaletteWithShortTrns, result.image.rgbaSnapshot())
    }

    // decodeAdmitted's ceiling check was `width.toLong() * height.toLong() * 4L > maximumDecodedBytes`:
    // correct in isolation, but width/height alone can each be up to 2^31-1 (scanPng's own admitted
    // range), and multiplying two such values together AND by 4 overflows signed 64-bit Long, wrapping
    // to a negative number that is never greater than any positive ceiling. Two distinct-magnitude
    // fixtures pin two distinct failure shapes of the same root cause; neither carries real IDAT data
    // (nor needs to — the ceiling check must reject before ever looking at pixel data), and the third
    // assertion proves the fix isn't simply "reject everything".
    @Test
    fun ceilingArithmeticNeverOverflowsForAnyAdmittedDimensionPair() {
        // width = height = 2^31-1: the exact per-dimension maximum DIMENSION_OUT_OF_RANGE admits. True
        // declared size is ~1.8e19 bytes; unfixed, `width*height*4L` wraps to -17179869180, which is
        // never > any positive ceiling, so a 45-byte file (no IDAT needed) defeats TooLarge entirely and
        // crashes several calls downstream instead (see the litmus in task-5-report.md).
        assertIs<PngDecodeResult.TooLarge>(decodePng(maxDimensionSquare, 100_000_000L))

        // width=1518500249, height=1518500253: both comfortably under 2^31-1 individually, but the true
        // width*height*4 (9223372049148251988) still exceeds Long.MAX_VALUE and wraps. Unfixed, that
        // wrapped ceiling-check value is negative too, so TooLarge never fires here either; downstream,
        // rawSizeLong.toInt() truncates to a SMALL POSITIVE 296902002, so the JVM actually allocates
        // ~283MB against this 100MB ceiling — no exception, no rejection, the ceiling simply silently
        // does not apply (see the litmus in task-5-report.md for the reproduced figures).
        assertIs<PngDecodeResult.TooLarge>(decodePng(wrappingProductDimensions, 100_000_000L))

        // Proves the fix isn't "reject everything": a real, legitimately large image exactly at its
        // ceiling (the existing 4096x4096 fixture and ceiling from
        // decidesTheCeilingFromHeaderDimensionsBeforeAllocating) still decodes.
        assertIs<PngDecodeResult.Success>(decodePng(declared4096Square, 67_108_864L))
    }

    private fun malformedReasonOf(bytes: ByteArray): PngReject =
        assertIs<PngDecodeResult.Malformed>(decodePng(bytes, 1L shl 20)).reason

    // Not in the brief's literal test list. The brief's own context claims Task 4 already proves a
    // split IDAT stream "reassembles to identical scanlines", but PngContainerTest only asserts the
    // range COUNT for its split fixture (rgb8SplitImageData), never decodes it — scanPng never inflates
    // anything. So this is the one test that actually exercises feeding several non-chunk-aligned,
    // mid-symbol IDAT ranges into a single InflateStream in order, which is exactly the risk this
    // decoder's `inflateExactly` carries.
    @Test
    fun reassemblesAZlibStreamSplitAcrossThreeNonChunkAlignedIdatRanges() {
        val result = assertIs<PngDecodeResult.Success>(decodePng(multiIdatSplitImage, 1L shl 20))
        assertContentEquals(expectedMultiIdatSplitPixels, result.image.rgbaSnapshot())
    }

    private val expectedFilterPixels: ByteArray = byteArrayOf(
        2, 5, 8, -1, 3, 12, 18, -1, 15, 22, 28, -1, 25, 32, 38, -1, 0, 42, 48, -1, 50, 52, 58, -1,
        45, 62, 68, -1, 55, 72, 78, -1, 65, 1, 25, -1, 75, 3, 35, -1, 85, 45, 45, -1, 95, 55, 55, -1,
        125, 0, -111, -1, -121, 90, -101, -1, -111, 105, -91, -1, -101, 115, -81, -1
    )

    private val filterNoneFixture: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4,
        8, 2, 0, 0, 0, 38, -109, 9, 41, 0, 0, 0, 60, 73, 68, 65, 84, 120, -38, 99, 96, 98, -27, 96,
        -26, 17, -30, 23, -109, -111, 84, 80, 99, 96, -48, 50, 48, 50, -79, -46, -75, 115, 49, -9, -16, 99, 112, 100,
        -108, -12, 102, 86, 14, -43, -43, -115, 55, 55, 103, -88, 101, -104, -40, 30, 53, 123, 98, -26, -46, -39, -59, -21,
        1, -66, 91, 11, 117, -64, -52, -47, -15, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val filterSubFixture: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4,
        8, 2, 0, 0, 0, 38, -109, 9, 41, 0, 0, 0, 48, 73, 68, 65, 84, 120, -38, 99, 100, 98, -27, 96,
        100, -25, -30, -31, 2, 1, 70, 6, 45, 3, 35, 46, -82, -33, 16, -114, 35, -93, 36, 23, 19, 23, -105, 22,
        -104, 83, -53, 48, -111, 43, -118, -117, -117, 31, -60, 1, 0, 109, 0, 4, -69, 76, -16, -33, 105, 0, 0, 0,
        0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val filterUpFixture: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4,
        8, 2, 0, 0, 0, 38, -109, 9, 41, 0, 0, 0, 52, 73, 68, 65, 84, 120, -38, 99, 98, 98, -27, 96,
        -26, 17, -30, 23, -109, -111, 84, 80, 99, -6, -89, -86, -95, -81, -95, 33, 7, 70, 76, -114, -41, 95, 74, -98,
        127, -87, -15, 30, -124, -104, 108, -2, 87, -40, -124, 87, -40, -40, -128, 16, 0, 53, 60, 15, -17, -53, 86, -7,
        -118, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val filterAverageFixture: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4,
        8, 2, 0, 0, 0, 38, -109, 9, 41, 0, 0, 0, 61, 73, 68, 65, 84, 120, -38, 99, 102, 98, -27, 96,
        -30, -30, -29, 19, 16, 22, 18, -107, 96, -2, -81, -95, 99, 40, 41, -55, 43, 41, 41, 34, 41, -55, -20, -8,
        -122, 81, -24, -27, 47, 73, -34, 95, -110, 127, 127, 49, -57, 50, -76, 42, 71, 58, 42, -85, 57, 42, 43, 59,
        2, 0, -13, 39, 11, -28, -40, -70, -32, -60, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val filterPaethFixture: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4,
        8, 2, 0, 0, 0, 38, -109, 9, 41, 0, 0, 0, 52, 73, 68, 65, 84, 120, -38, 99, 97, 98, -27, 96,
        100, -25, -30, -31, 2, 1, -106, 127, -86, 26, 70, 92, 92, -65, 33, 28, -57, -21, 47, -71, -104, -72, -72, -76,
        -72, -72, 126, 114, -79, -40, -4, -81, -32, 10, -25, -30, -30, 7, -55, 0, 0, -51, -7, 8, -17, 98, 114, 77,
        -26, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val grey8TwoPixels: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 1,
        8, 0, 0, 0, 0, -47, 73, 32, 86, 0, 0, 0, 11, 73, 68, 65, 84, 120, -38, 99, 112, 104, 0, 0,
        1, 3, 0, -63, 71, -123, -105, 29, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val paletteWithTrns: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 1,
        8, 3, 0, 0, 0, -61, -4, -113, -72, 0, 0, 0, 6, 80, 76, 84, 69, -1, 0, 0, 0, 0, -1, 108,
        -95, -3, -114, 0, 0, 0, 2, 116, 82, 78, 83, -1, -128, 8, 15, -77, 106, 0, 0, 0, 11, 73, 68, 65,
        84, 120, -38, 99, 96, 96, 4, 0, 0, 4, 0, 2, 44, -34, 72, -83, 0, 0, 0, 0, 73, 69, 78, 68,
        -82, 66, 96, -126
    )

    private val filterByteFive: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 2, 0, 0, 0, -112, 119, 83, -34, 0, 0, 0, 12, 73, 68, 65, 84, 120, -38, 99, -27, 18, -111, 3,
        0, 0, 124, 0, 66, -5, -9, 82, 21, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val deflateShorterThanRaster: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 0, 0, 0, 0, 87, -35, 82, -8, 0, 0, 0, 11, 73, 68, 65, 84, 120, -38, 99, -32, 18, 1, 0,
        0, 43, 0, 31, 4, -56, -16, -62, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val deflateLongerThanRaster: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 0, 0, 0, 0, 87, -35, 82, -8, 0, 0, 0, 17, 73, 68, 65, 84, 120, -38, 99, -32, 18, 97, -112,
        -45, 96, 48, -78, 1, 0, 2, -69, 0, -45, 28, -73, 124, -38, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66,
        96, -126
    )

    // A real, valid 4096x4096 greyscale PNG (all-zero pixels, filter 0) — the smallest realistic
    // fixture that still lets decidesTheCeilingFromHeaderDimensionsBeforeAllocating declare exactly
    // the header the test comment describes. Its compressed IDAT is ~16KB even at zlib level 9 (a
    // deflate match tops out at 258 bytes, so ~65,000 matches is close to the floor for 16,781,312
    // raw bytes), which as a plain `byteArrayOf(...)` element list overflows the JVM class file
    // format's 64KB-per-method bytecode limit (`Method too large: <init>`), since every instance
    // property initializer compiles into the same constructor. Base64, decoded once via the stable
    // stdlib API, keeps this as one compact string constant instead of ~16,378 store instructions.
    @OptIn(kotlin.io.encoding.ExperimentalEncodingApi::class)
    private val declared4096Square: ByteArray = kotlin.io.encoding.Base64.decode(
        "iVBORw0KGgoAAAANSUhEUgAAEAAAABAACAAAAADXyHvLAAA/wUlEQVR42uzBAQEAAACAkP6v7ggKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA2YMDAQAAAAAg/9dGUFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVWEPDgQAAAAAgPxfG0FVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWlPTggAQAAABD0/3U/QgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAuAofAAABZJsp9gAAAABJRU5ErkJggg=="
    )


    private val rgb8Reference: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 22, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 102,
        97, 101, 99, 96, -25, -32, -28, -30, -26, 1, 0, 1, -113, 0, 79, 6, -88, -27, -118, 0, 0, 0, 0, 73,
        69, 78, 68, -82, 66, 96, -126
    )

    private val expectedRgb8ReferencePixels: ByteArray = byteArrayOf(
        1, 2, 3, -1, 4, 5, 6, -1, 7, 8, 9, -1, 10, 11, 12, -1
    )

    private val rgb8WithGama: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 4, 103, 65, 77, 65, 0, 0, -79, -113, 11, -4, 97,
        5, 0, 0, 0, 22, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 102, 97, 101, 99, 96, -25, -32, -28, -30,
        -26, 1, 0, 1, -113, 0, 79, 6, -88, -27, -118, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val rgb8WithSrgb: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 1, 115, 82, 71, 66, 0, -82, -50, 28, -23, 0, 0,
        0, 22, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 102, 97, 101, 99, 96, -25, -32, -28, -30, -26, 1, 0,
        1, -113, 0, 79, 6, -88, -27, -118, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val rgb8WithIccp: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 32, 105, 67, 67, 80, 112, 114, 111, 102, 105, 108, 101,
        0, 0, 120, -100, 75, 75, -52, 78, 45, 40, -54, 79, -53, -52, 73, 77, 73, 44, 73, 4, 0, 49, 57, 6,
        35, 65, -34, -57, -31, 0, 0, 0, 22, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 102, 97, 101, 99, 96,
        -25, -32, -28, -30, -26, 1, 0, 1, -113, 0, 79, 6, -88, -27, -118, 0, 0, 0, 0, 73, 69, 78, 68, -82,
        66, 96, -126
    )

    private val rgb8WithChrm: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 32, 99, 72, 82, 77, 0, 0, 122, 38, 0, 0, -128,
        -124, 0, 0, -6, 0, 0, 0, -128, -24, 0, 0, 117, 48, 0, 0, -22, 96, 0, 0, 58, -104, 0, 0, 23,
        112, -100, -70, 81, 60, 0, 0, 0, 22, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 102, 97, 101, 99, 96,
        -25, -32, -28, -30, -26, 1, 0, 1, -113, 0, 79, 6, -88, -27, -118, 0, 0, 0, 0, 73, 69, 78, 68, -82,
        66, 96, -126
    )

    private val greyAlphaWithForbiddenTrns: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 4, 0, 0, 0, -75, 28, 12, 2, 0, 0, 0, 2, 116, 82, 78, 83, 0, 50, -66, 68, -100, -72, 0,
        0, 0, 11, 73, 68, 65, 84, 120, -38, 99, 72, 57, 1, 0, 1, -109, 1, 45, 18, -25, -55, -111, 0, 0,
        0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val rgbaWithForbiddenTrns: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 6, 0, 0, 0, 31, 21, -60, -119, 0, 0, 0, 6, 116, 82, 78, 83, 1, 2, 3, 4, 5, 6, 94,
        -110, -47, 22, 0, 0, 0, 13, 73, 68, 65, 84, 120, -38, 99, -32, 18, -111, -5, 15, 0, 1, -92, 1, 60,
        76, -43, 28, -89, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // Colour type 3, PLTE with exactly one entry (10,20,30), raster is a single pixel with index byte
    // 5 — out of range, since only index 0 is valid for a one-entry palette.
    private val paletteIndexOutOfRange: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 3, 0, 0, 0, 40, -53, 52, -69, 0, 0, 0, 3, 80, 76, 84, 69, 10, 20, 30, 126, 76, 82, 58,
        0, 0, 0, 10, 73, 68, 65, 84, 120, -38, 99, 96, 5, 0, 0, 7, 0, 6, 45, 69, 24, 7, 0, 0,
        0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // IHDR declares width = 0x80000000 (2^31) — a value which, as an unchecked 32-bit
    // reinterpretation, wraps to a negative Int. height=1, depth=8, colour=2 (truecolour), a complete,
    // validly CRC'd file (real IDAT/IEND included, even though scanPng rejects from inside IHDR parsing
    // before it would ever need them).
    private val dimensionOutOfRange: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, -128, 0, 0, 0, 0, 0, 0, 1,
        8, 2, 0, 0, 0, -33, -33, 29, -9, 0, 0, 0, 12, 73, 68, 65, 84, 120, -38, 99, 96, 100, 98, 6,
        0, 0, 14, 0, 7, -23, -110, 55, -44, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // width=height=2^31-1 (the exact per-dimension maximum DIMENSION_OUT_OF_RANGE admits), colour type
    // 0, no IDAT chunk at all — scanPng never requires one, and the ceiling check must reject this
    // before ever looking at pixel data, so there is none to fake.
    private val maxDimensionSquare: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 127, -1, -1, -1, 127, -1, -1, -1,
        8, 0, 0, 0, 0, 49, -94, 84, -70, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // width=1518500249, height=1518500253 — both individually well within scanPng's admitted range,
    // but width*height*4 exceeds Long.MAX_VALUE. Colour type 0, no IDAT chunk (same reasoning as above).
    private val wrappingProductDimensions: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 90, -126, 121, -103, 90, -126, 121, -99,
        8, 0, 0, 0, 0, 55, 114, -107, -103, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // Colour type 0 (greyscale), 1x1, tRNS present but 0 bytes long (needs exactly 2).
    private val greyTrnsWrongLength: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 0, 0, 0, 0, 58, 126, -101, 85, 0, 0, 0, 0, 116, 82, 78, 83, 54, -71, 112, -52, 0, 0, 0,
        10, 73, 68, 65, 84, 120, -38, 99, 72, 1, 0, 0, 102, 0, 101, -41, 40, -68, 31, 0, 0, 0, 0, 73,
        69, 78, 68, -82, 66, 96, -126
    )

    // Colour type 2 (truecolour), 1x1, tRNS present but 4 bytes long (needs exactly 6).
    private val rgbTrnsWrongLength: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1,
        8, 2, 0, 0, 0, -112, 119, 83, -34, 0, 0, 0, 4, 116, 82, 78, 83, 0, 1, 2, 3, 25, 110, 63,
        -107, 0, 0, 0, 12, 73, 68, 65, 84, 120, -38, 99, -32, 18, -111, 3, 0, 0, 104, 0, 61, 106, -11, 112,
        91, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    // Colour type 0, 2x1, correctly-sized 2-byte tRNS keying grey value 0x50. Pixel 1 = 0x50 (keyed,
    // transparent), pixel 2 = 0x30 (not keyed, opaque).
    private val greyTwoPixelsWithTrnsKey: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 1,
        8, 0, 0, 0, 0, -47, 73, 32, 86, 0, 0, 0, 2, 116, 82, 78, 83, 0, 80, 29, -8, -100, -52, 0,
        0, 0, 11, 73, 68, 65, 84, 120, -38, 99, 8, 48, 0, 0, 0, -45, 0, -127, 107, -29, -87, 45, 0, 0,
        0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val expectedGreyTwoPixelsWithTrnsKey: ByteArray = byteArrayOf(
        80, 80, 80, 0, 48, 48, 48, -1
    )

    // Colour type 2, 2x1, correctly-sized 6-byte tRNS keying RGB (10,20,30). Pixel 1 = (10,20,30)
    // (keyed, transparent), pixel 2 = (40,50,60) (not keyed, opaque).
    private val rgbTwoPixelsWithTrnsKey: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 1,
        8, 2, 0, 0, 0, 123, 64, -24, -35, 0, 0, 0, 6, 116, 82, 78, 83, 0, 10, 0, 20, 0, 30, -59,
        54, 41, -1, 0, 0, 0, 15, 73, 68, 65, 84, 120, -38, 99, -32, 18, -111, -45, 48, -78, 1, 0, 2, 55,
        0, -45, -30, 45, -19, -97, 0, 0, 0, 0, 73, 69, 78, 68, -82, 66, 96, -126
    )

    private val expectedRgbTwoPixelsWithTrnsKey: ByteArray = byteArrayOf(
        10, 20, 30, 0, 40, 50, 60, -1
    )

    // Colour type 3, 3x1, PLTE with 3 entries but tRNS with only 1 entry (alpha for index 0 = 200);
    // indices 1 and 2 have no tRNS entry and must default to opaque (specification-mandated leniency).
    private val paletteWithShortTrns: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 3, 0, 0, 0, 1,
        8, 3, 0, 0, 0, 44, 62, -28, -122, 0, 0, 0, 9, 80, 76, 84, 69, 100, 0, 0, 0, 100, 0, 0,
        0, 100, -92, -127, 77, -92, 0, 0, 0, 1, 116, 82, 78, 83, -56, -43, 89, -110, -28, 0, 0, 0, 12, 73,
        68, 65, 84, 120, -38, 99, 96, 96, 100, 2, 0, 0, 8, 0, 4, 8, 29, 99, 10, 0, 0, 0, 0, 73,
        69, 78, 68, -82, 66, 96, -126
    )

    private val expectedPaletteWithShortTrns: ByteArray = byteArrayOf(
        100, 0, 0, -56, 0, 100, 0, -1, 0, 0, 100, -1
    )

    private val multiIdatSplitImage: ByteArray = byteArrayOf(
        -119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 2, 0, 0, 0, 2,
        8, 2, 0, 0, 0, -3, -44, -102, 115, 0, 0, 0, 7, 73, 68, 65, 84, 120, -38, 99, 56, 113, -14, -44,
        60, 126, 48, 103, 0, 0, 0, 8, 73, 68, 65, 84, -23, 51, 103, 25, -50, -99, -65, 112, -61, 92, 103, -50,
        0, 0, 0, 8, 73, 68, 65, 84, -15, -46, 101, 0, 66, -37, 9, -93, -105, 48, -58, -86, 0, 0, 0, 0,
        73, 69, 78, 68, -82, 66, 96, -126
    )

    private val expectedMultiIdatSplitPixels: ByteArray = byteArrayOf(
        -56, -55, -54, -1, -53, -52, -51, -1, -50, -49, -48, -1, -47, -46, -45, -1
    )

    private val filterFixtures: List<Pair<String, ByteArray>> = listOf(
        "filterNone" to filterNoneFixture,
        "filterSub" to filterSubFixture,
        "filterUp" to filterUpFixture,
        "filterAverage" to filterAverageFixture,
        "filterPaeth" to filterPaethFixture,
    )
}
