package com.rohittp.reng.internal.gl

internal enum class GlEntryPoint(internal val cName: String) {
    GET_ERROR("glGetError"),
    GET_STRING("glGetString"),
    GET_STRINGI("glGetStringi"),
    GET_INTEGERV("glGetIntegerv"),
    GET_FLOATV("glGetFloatv"),
    GET_BOOLEANV("glGetBooleanv"),
    IS_ENABLED("glIsEnabled"),

    GEN_FRAMEBUFFERS("glGenFramebuffers"),
    DELETE_FRAMEBUFFERS("glDeleteFramebuffers"),
    BIND_FRAMEBUFFER("glBindFramebuffer"),
    FRAMEBUFFER_TEXTURE_2D("glFramebufferTexture2D"),
    FRAMEBUFFER_RENDERBUFFER("glFramebufferRenderbuffer"),
    CHECK_FRAMEBUFFER_STATUS("glCheckFramebufferStatus"),
    IS_FRAMEBUFFER("glIsFramebuffer"),
    GEN_RENDERBUFFERS("glGenRenderbuffers"),
    DELETE_RENDERBUFFERS("glDeleteRenderbuffers"),
    BIND_RENDERBUFFER("glBindRenderbuffer"),
    RENDERBUFFER_STORAGE("glRenderbufferStorage"),
    BLIT_FRAMEBUFFER("glBlitFramebuffer"),
    DRAW_BUFFERS("glDrawBuffers"),
    READ_BUFFER("glReadBuffer"),

    GEN_TEXTURES("glGenTextures"),
    DELETE_TEXTURES("glDeleteTextures"),
    BIND_TEXTURE("glBindTexture"),
    ACTIVE_TEXTURE("glActiveTexture"),
    TEX_IMAGE_2D("glTexImage2D"),
    TEX_STORAGE_2D("glTexStorage2D"),
    TEX_PARAMETERI("glTexParameteri"),
    GENERATE_MIPMAP("glGenerateMipmap"),
    GEN_SAMPLERS("glGenSamplers"),
    DELETE_SAMPLERS("glDeleteSamplers"),
    BIND_SAMPLER("glBindSampler"),
    SAMPLER_PARAMETERI("glSamplerParameteri"),
    PIXEL_STOREI("glPixelStorei"),
    READ_PIXELS("glReadPixels"),

    GEN_BUFFERS("glGenBuffers"),
    DELETE_BUFFERS("glDeleteBuffers"),
    BIND_BUFFER("glBindBuffer"),
    BUFFER_DATA("glBufferData"),
    BUFFER_SUB_DATA("glBufferSubData"),
    GEN_VERTEX_ARRAYS("glGenVertexArrays"),
    DELETE_VERTEX_ARRAYS("glDeleteVertexArrays"),
    BIND_VERTEX_ARRAY("glBindVertexArray"),
    ENABLE_VERTEX_ATTRIB_ARRAY("glEnableVertexAttribArray"),
    DISABLE_VERTEX_ATTRIB_ARRAY("glDisableVertexAttribArray"),
    VERTEX_ATTRIB_POINTER("glVertexAttribPointer"),

    CREATE_SHADER("glCreateShader"),
    DELETE_SHADER("glDeleteShader"),
    SHADER_SOURCE("glShaderSource"),
    COMPILE_SHADER("glCompileShader"),
    GET_SHADERIV("glGetShaderiv"),
    GET_SHADER_INFO_LOG("glGetShaderInfoLog"),
    CREATE_PROGRAM("glCreateProgram"),
    DELETE_PROGRAM("glDeleteProgram"),
    ATTACH_SHADER("glAttachShader"),
    LINK_PROGRAM("glLinkProgram"),
    GET_PROGRAMIV("glGetProgramiv"),
    GET_PROGRAM_INFO_LOG("glGetProgramInfoLog"),
    USE_PROGRAM("glUseProgram"),
    GET_ATTRIB_LOCATION("glGetAttribLocation"),
    GET_UNIFORM_LOCATION("glGetUniformLocation"),
    UNIFORM_1I("glUniform1i"),
    UNIFORM_1F("glUniform1f"),
    UNIFORM_2F("glUniform2f"),
    UNIFORM_3F("glUniform3f"),
    UNIFORM_4F("glUniform4f"),
    UNIFORM_1UI("glUniform1ui"),
    UNIFORM_MATRIX_4FV("glUniformMatrix4fv"),

    ENABLE("glEnable"),
    DISABLE("glDisable"),
    BLEND_FUNC_SEPARATE("glBlendFuncSeparate"),
    BLEND_EQUATION_SEPARATE("glBlendEquationSeparate"),
    BLEND_COLOR("glBlendColor"),
    DEPTH_FUNC("glDepthFunc"),
    DEPTH_MASK("glDepthMask"),
    DEPTH_RANGEF("glDepthRangef"),
    CULL_FACE("glCullFace"),
    FRONT_FACE("glFrontFace"),
    VIEWPORT("glViewport"),
    SCISSOR("glScissor"),
    COLOR_MASK("glColorMask"),
    CLEAR_COLOR("glClearColor"),
    CLEAR_DEPTHF("glClearDepthf"),
    CLEAR("glClear"),
    DRAW_ARRAYS("glDrawArrays"),
    DRAW_ELEMENTS("glDrawElements"),
    FINISH("glFinish"),

    // Uniform buffers, added for skinning: joint counts in the consumer's own corpus reach 112,
    // and GLSL ES 3.00 guarantees only 64 mat4 of vertex uniforms, so joint matrices travel in a
    // uniform buffer instead. Appended after FINISH rather than interleaved so every existing
    // GlEntryPoint.ordinal — which LinuxGlBinding indexes its resolved function-pointer table by —
    // stays unchanged.
    BIND_BUFFER_BASE("glBindBufferBase"),
    GET_UNIFORM_BLOCK_INDEX("glGetUniformBlockIndex"),
    UNIFORM_BLOCK_BINDING("glUniformBlockBinding"),
    GET_INTEGERI_V("glGetIntegeri_v"),
    // Appended so every existing Linux function-table ordinal remains stable.
    TEX_SUB_IMAGE_2D("glTexSubImage2D"),
}
